export enum TokenType {
    RESOURCE = "RESOURCE",
    SUBJECT = "SUBJECT",
    RELATION = "RELATION",
    PERMISSION = "PERMISSION",

    AND = "AND",
    OR = "OR",
    NOT = "NOT",

    BOOLEAN_LITERAL = "BOOLEAN_LITERAL",
    IDENTIFIER = "IDENTIFIER",

    LBRACE = "LBRACE",
    RBRACE = "RBRACE",
    LPAREN = "LPAREN",
    RPAREN = "RPAREN",

    EQUALS = "EQUALS",
    COLON = "COLON",
    ARROW = "ARROW",

    EOF = "EOF"
}
